# Checking for duplicates in a DataFrame


In this session, you will learn how to find duplicate rows in a Dataframe based on all or a list of columns. For this we will use `.duplicated()` method on the DataFrame.

---

Let’s import course attendance DataFrame from our datasets directory to see how we can remove duplicates from the DataFrame.

Load the Ethiopian's flowers dataset (.csv) that was adapted from the well known Iris dataset. Remember the first thing is to import all the necessary libraries such as numpy, pandas, etc.

In [1]:
import numpy as np
import pandas as pd

In [2]:
course_attendance = pd.read_csv("datasets/course attendance.csv")

It is a small dataset so we can easily print it out

In [3]:
course_attendance

         Name Gender  Age      Country Course taken
0      Aadaan      M   16      Somalia       CS 1 2
1     Francis      M   18        Kenya       CS 1 3
2     Aamiina      F   20      Somalia       CS 1 5
3     Ibrahim      M   20  South Sudan       CS 1 3
4        Getu      M   16     Ethiopia       CS 2 2
5   Francisca      F   16       Uganda       CS 1 6
6       Simon      M   19  South Sudan       CS 2 2
7        Abiy      M   19     Ethiopia       CS 2 3
8     Abreham      M   20    Ethiopian       CS 1 5
9      Abshir      M   20      Somalia        CS 24
10      Jamal      M   18  South Sudan       CS 1 2
11      Allan      M   19        Kenya        CS 21
12     Mariam      F   20       Uganda       CS 3 1
13  Francisca      F   16       Uganda       CS 1 6
14      Aliya      F   18       Uganda       CS 3 1
15    Francis      M   18        Kenya       CS 1 3
16      Simon      M   19  South Sudan       CS 2 2

## Example 1 : Select duplicate rows based on all columns.

Here, We do not pass any argument therefore it takes default values for both the arguments i.e. `subset = None` and `keep = "first"`. Selecting duplicate rows except first occurrence based on all columns. 

The code is `course_attendance[course_attendance.duplicated()]`. Let's break it one by one for your understanding.

**Step 1**: Check for duplicate rows using `.duplicated()` method. This results to Boolean Series (True/False) denoting duplicate rows.

In [4]:
course_attendance.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15     True
16     True
dtype: bool

As you can see, we have some missing values in row 14, 16, and 17 respectively. Remember Python index starts with 0. To check for the number  of duplicates use:

In [5]:
course_attendance.duplicated().sum()

3

**Step 2**: Use the result of step 1 to select the duplicate rows in the DataFrame i.e. `DataFrame[step1]`.

In [7]:
course_attendance[course_attendance.duplicated()]

         Name Gender  Age      Country Course taken
13  Francisca      F   16       Uganda       CS 1 6
15    Francis      M   18        Kenya       CS 1 3
16      Simon      M   19  South Sudan       CS 2 2

## Example 2 : Select duplicate rows based on all columns

Or do it with just one line of code

In [7]:
course_attendance[course_attendance.duplicated()]

         Name Gender  Age      Country Course taken
13  Francisca      F   16       Uganda       CS 1 6
15    Francis      M   18        Kenya       CS 1 3
16      Simon      M   19  South Sudan       CS 2 2

## Example 3 : Select duplicate rows based on some columns

If you want to select duplicate rows based only on some selected columns then pass the list of column names in subset as an argument.

In [157]:
course_attendance[course_attendance.duplicated("Name")]

         Name Gender  Age      Country Course taken
13  Francisca      F   16       Uganda       CS 1 6
15    Francis      M   18        Kenya       CS 1 3
16      Simon      M   19  South Sudan       CS 2 2

In [158]:
course_attendance[course_attendance.duplicated("Course taken")]

         Name Gender  Age      Country Course taken
3     Ibrahim      M   20  South Sudan       CS 1 3
6       Simon      M   19  South Sudan       CS 2 2
8     Abreham      M   20    Ethiopian       CS 1 5
10      Jamal      M   18  South Sudan       CS 1 2
13  Francisca      F   16       Uganda       CS 1 6
14      Aliya      F   18       Uganda       CS 3 1
15    Francis      M   18        Kenya       CS 1 3
16      Simon      M   19  South Sudan       CS 2 2

## Example 4 : Select duplicate rows based on some columns

Select duplicate rows based on more than one column names

In [159]:
course_attendance[course_attendance.duplicated(["Name", "Country"])]

         Name Gender  Age      Country Course taken
13  Francisca      F   16       Uganda       CS 1 6
15    Francis      M   18        Kenya       CS 1 3
16      Simon      M   19  South Sudan       CS 2 2