# <font color=blue> Introduction to Data Analysis with Pandas
    
<img src='images/Pandas.png' alt = "Pandas" style="width:600; height:300"/>

## Objectives

In this section of the course, students will learn how to use pandas for importing data, data cleaning, and analysis. Students can think of Pandas as an extremely powerful version of spreadsheet like Microsoft Excel, with a lot more features. At the end of the course, students will be able to import, clean, and do various data analysis with Pandas.

## Importing the Pandas library

To import pandas we usually import it with its alias, `pd`

In [1]:
import pandas as pd

## Core components of pandas

The two primary components of pandas are the Series and DataFrame. A `Series` is essentially a column, and a `DataFrame` is a multi-dimensional table made up of a collection of Series.

![](images/dataframe.jpg)

# Series and DataFrame

## Pandas Series
A Series is a one-dimensional array-like object containing a sequence of values and capable of holding any data type with axis labels or index. An example of a Series object is one column from a DataFrame. That is, Pandas Series is formed from only an array of data.

## How to create Pandas Series

![](images/dataframe.jpg)

### Example 1

In [2]:
Gender = pd.Series(["Male", "Female", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female"])

Gender

0      Male
1    Female
2    Female
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
dtype: object

In [8]:
type(Gender) # This is a pandas series type

pandas.core.series.Series

### Example 2

In [3]:
Country = pd.Series(["Uganda", "Ethiopia", "Rwanda", "Somalia", "Sudan", "Kenya", "Uganda", "Kenya", "Somalia", "Rwanda"])
Country

0      Uganda
1    Ethiopia
2      Rwanda
3     Somalia
4       Sudan
5       Kenya
6      Uganda
7       Kenya
8     Somalia
9      Rwanda
dtype: object

In [10]:
type(Country)

pandas.core.series.Series

### Example 3

In [11]:
Age = pd.Series([11, 17, 15, 17, 13, 11, 9, 18, 13, 16])
Age

0    11
1    17
2    15
3    17
4    13
5    11
6     9
7    18
8    13
9    16
dtype: int64

In [12]:
type(Age)

pandas.core.series.Series

## Pandas DataFrame

A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (integer, float, string, boolean, etc.). We can think of a DataFrame as a bunch of Series objects put together to share the same index.

## How to create Pandas DataFrame

There are many ways to create a DataFrame from scratch, but a great option is to create it from a dictionary.

### Creating DataFrame from a Dictionary

Among the many things that can serve as input to make a Pandas `DataFrame` is a `dict` (Dictionary). To make a data frame from a dictionary, you will need to pass it to the DataFrame() function in the data argument.

### Example 1

![](images/dd.jpg)

In [4]:
registrations_dict = {
    "Gender": ["Male", "Female", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
"Country": ["Uganda", "Ethiopia", "Rwanda", "Somalia", "Sudan", "Kenya", "Uganda", "Kenya", "Somalia", "Rwanda"],
"Age": [11, 17, 15, 17, 13, 11, 9, 18, 13, 16]
}

registrations_dict

{'Gender': ['Male',
  'Female',
  'Female',
  'Female',
  'Male',
  'Female',
  'Male',
  'Female',
  'Male',
  'Female'],
 'Country': ['Uganda',
  'Ethiopia',
  'Rwanda',
  'Somalia',
  'Sudan',
  'Kenya',
  'Uganda',
  'Kenya',
  'Somalia',
  'Rwanda'],
 'Age': [11, 17, 15, 17, 13, 11, 9, 18, 13, 16]}

In [5]:
type(registrations_dict)

dict

And then pass the result to the pandas DataFrame constructor:

In [6]:
registrations_df = pd.DataFrame(registrations_dict)

registrations_df

   Gender   Country  Age
0    Male    Uganda   11
1  Female  Ethiopia   17
2  Female    Rwanda   15
3  Female   Somalia   17
4    Male     Sudan   13
5  Female     Kenya   11
6    Male    Uganda    9
7  Female     Kenya   18
8    Male   Somalia   13
9  Female    Rwanda   16

The resulting DataFrame will have its index assigned automatically as with Series, and the columns are placed unordered. If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order.

In [7]:
registrations_df = pd.DataFrame(registrations_dict, columns = ["Country", "Gender", "Age"])

registrations_df

    Country  Gender  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

## Example 2

This example is for corona virus (COVID-19) report as of November 25, 2020.

In [8]:
COVID19data = { "Country": ["Burundi", "Ethiopia", "Kenya", "Rwanda", "Somalia", "Tanzania", "Uganda", "Sudan"],
               "Total Cases": [673, 107109, 79322, 5750, 4445, 509, 18406, 16431],
               "Total Deaths": [1, 1664, 1417, 47, 113, 21, 186, 1202],
               "Total Recovered": [575, 66574, 52974, 5241, 3412, 183, 8764, 9854],
               "Active Cases" : [97, 38871, 24931, 462, 920, 305, 9456, 5375],
               "Population" : [12029114, 116082175, 54237961, 13078334, 16066789, 60399786, 46304101, 44252054]
}

COVID19data_df = pd.DataFrame(COVID19data, columns= ["Country", "Total Cases", "Total Deaths", "Total Recovered", "Active Cases", "Population"])

COVID19data_df

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

We shall be using `registrations_df` and `COVID19data_df` dataframes in our various examples henceforth.

### Viewing your data

For large DataFrames, we can select the first five observations or rows by using `.head()` attribute and the last five observation by using `.tail()` attribute.

### Example 1

In [9]:
registrations_df.head()

    Country  Gender  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13

In [10]:
registrations_df.tail()

   Country  Gender  Age
5    Kenya  Female   11
6   Uganda    Male    9
7    Kenya  Female   18
8  Somalia    Male   13
9   Rwanda  Female   16

## Example 2

In [11]:
COVID19data_df.head(7)

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101

In [12]:
COVID19data_df.tail(3)

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

## Getting information about your data

### .info() method

`.info()` attribute provides the essential details about your dataset, such as the number of rows and columns, the number of non-null values, what type of data is in each column, and how much memory your DataFrame is using.

## Example 1

In [13]:
registrations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  10 non-null     object
 1   Gender   10 non-null     object
 2   Age      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes

Seeing the datatype quickly is actually quite useful in data cleaning and analysis phases

## Example 2

In [14]:
COVID19data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          8 non-null      object
 1   Total Cases      8 non-null      int64
 2   Total Deaths     8 non-null      int64
 3   Total Recovered  8 non-null      int64
 4   Active Cases     8 non-null      int64
 5   Population       8 non-null      int64
dtypes: int64(5), object(1)
memory usage: 512.0+ bytes

### .shape method

Another useful attribute is `.shape`, which outputs just a tuple of (rows, columns):

## Example 1

In [15]:
registrations_df.shape

(10, 3)

The students registration data has $10$ rows and $3$ columns.

Note that `.shape` has no parentheses and is a simple tuple of format (rows, columns). So we have $10$ rows and $3$ columns in our students registration DataFrame.

## Example 2

In [16]:
COVID19data_df.shape

(8, 6)

The COVID-19 has $8$ rows and $6$ columns.

It is important to note that you will be going to `.shape` a lot when cleaning and transforming data. For example, you might filter some rows based on some criteria and then want to know quickly how many rows were removed or left in the dataset.

## Display the index and columns in a DataFrame
We can use `.index` and `.column` attribute to see the list of observations and column names in our dataframe.

## Example 1

Let's check the index and columns in the students registration dataframe

In [17]:
registrations_df.index

RangeIndex(start=0, stop=10, step=1)

The observation/index is from $0$ to $9$. Remember Numpy array, $0:10$ means $0, 1, 2$, $\cdots$, $9$.

In [18]:
registrations_df.columns

Index(['Country', 'Gender', 'Age'], dtype='object')

The column names in the students registration dataframe are Country, Gender, and Age.

## Example 2
Let's check the columns in the COVID-19 dataframe

In [19]:
COVID19data_df.columns

Index(['Country', 'Total Cases', 'Total Deaths', 'Total Recovered',
       'Active Cases', 'Population'],
      dtype='object')

The column names in the COVID-19 data are Country, Total Cases, Total Deaths, Tota Recovered, Active Cases, and Popuation

# Selection and Indexing of DataFrame

Let's learn the various methods to grab data from a DataFrame.

## Example 1

Remember our students registration dataframe:

In [20]:
registrations_df

    Country  Gender  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

A column in a DataFrame can be retrieved as a Series:

In [21]:
registrations_df['Country']

0      Uganda
1    Ethiopia
2      Rwanda
3     Somalia
4       Sudan
5       Kenya
6      Uganda
7       Kenya
8     Somalia
9      Rwanda
Name: Country, dtype: object

In [22]:
registrations_df["Age"]

0    11
1    17
2    15
3    17
4    13
5    11
6     9
7    18
8    13
9    16
Name: Age, dtype: int64

In [23]:
registrations_df.Gender

0      Male
1    Female
2    Female
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: Gender, dtype: object

In [24]:
registrations_df["Gender"]

0      Male
1    Female
2    Female
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: Gender, dtype: object

In [25]:
registrations_df.Age

0    11
1    17
2    15
3    17
4    13
5    11
6     9
7    18
8    13
9    16
Name: Age, dtype: int64

In [26]:
COVID19data_df

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

In [27]:
COVID19data_df.Total Cases

SyntaxError: invalid syntax (<ipython-input-27-7241c8041296>, line 1)

In [ ]:
COVID19data_df["Total Cases"]

**Important note**

`registrations_df['column']` works for any column name, but `registrations_df.column` only works when the column name is a valid Python variable name. That is, it follows Python naming convention (no space, no special character, not starting with number, etc.)

## Selecting two or more columns in a dataframe

We pass a list of column names to select two or more columns in a dataframe

## Example 1

In [28]:
registrations_df

    Country  Gender  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

In [29]:
registrations_df[["Country", "Gender"]]

    Country  Gender
0    Uganda    Male
1  Ethiopia  Female
2    Rwanda  Female
3   Somalia  Female
4     Sudan    Male
5     Kenya  Female
6    Uganda    Male
7     Kenya  Female
8   Somalia    Male
9    Rwanda  Female

## Example 2

In [30]:
COVID19data_df # Did you remember this dataframe?

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

In [31]:
COVID19data_df[["Country", "Population", "Total Cases"]] # Total Cases is COVID-19 cases

    Country  Population  Total Cases
0   Burundi    12029114          673
1  Ethiopia   116082175       107109
2     Kenya    54237961        79322
3    Rwanda    13078334         5750
4   Somalia    16066789         4445
5  Tanzania    60399786          509
6    Uganda    46304101        18406
7     Sudan    44252054        16431

In [32]:
COVID19data_df[["Country", "Population"]]

    Country  Population
0   Burundi    12029114
1  Ethiopia   116082175
2     Kenya    54237961
3    Rwanda    13078334
4   Somalia    16066789
5  Tanzania    60399786
6    Uganda    46304101
7     Sudan    44252054

# Selection with `.loc` and `.iloc` attribute

The `loc[]` and `iloc[]` DataFrame attribute enable you to select a subset of the rows and columns from a DataFrame with NumPy-like notation using either axis labels (`df.loc[]`) or integers (`df.iloc[]`). The general format for both `loc[]` and `iloc[]` are `df.loc[row, col]` and `df.iloc[row, col]` where `df`is the name of your DataFrame while the `[row, col]` specifies the row and column index of the DataFrame. Remember Python counting starts at 0, so the first row is row zero.

## .loc[]

As a preliminary example, let’s select first three rows and columns such as Country and Population by `using df.loc[]`.

## Example 1

`df.loc[row, col]` is for selection by column label.

In [33]:
COVID19data_df

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

In [34]:
COVID19data_df.loc[0:3, ["Country", "Population"]]

    Country  Population
0   Burundi    12029114
1  Ethiopia   116082175
2     Kenya    54237961
3    Rwanda    13078334

In [35]:
COVID19data_df.loc[ : , ["Country", "Total Deaths", "Population"] ]

    Country  Total Deaths  Population
0   Burundi             1    12029114
1  Ethiopia          1664   116082175
2     Kenya          1417    54237961
3    Rwanda            47    13078334
4   Somalia           113    16066789
5  Tanzania            21    60399786
6    Uganda           186    46304101
7     Sudan          1202    44252054

In example 1, we selected the first three observations and variables Country and Population. 

**Important note**

Please note that `.loc` index position is inclusive i.e. $0 : 5$ means $0, 1, 2, 3, 4, 5$. This is different from Numpy array that $0 : 5$ is $0, 1, 2, 3, 4$.

## Example 2

`df.loc[row, col]` is for selection by column label.

In [36]:
COVID19data_df.loc[:, ["Country", "Total Cases"]]

    Country  Total Cases
0   Burundi          673
1  Ethiopia       107109
2     Kenya        79322
3    Rwanda         5750
4   Somalia         4445
5  Tanzania          509
6    Uganda        18406
7     Sudan        16431

We selected all the observations (`:`) and columns Country and COVID-19 Total Cases

## .iloc[]
`df.iloc[row, col]` is for selection by column index or position. First, let us see the column index by using `.columns` attribute

In [37]:
COVID19data_df.columns

Index(['Country', 'Total Cases', 'Total Deaths', 'Total Recovered',
       'Active Cases', 'Population'],
      dtype='object')

Columns: 'Country'  'Total Cases' 'Total Deaths'  'Tota Recovered'   'Active Cases' 'Population'
    
Index:       0            1             2               3                 4                5

The columns Country and Population correspond to 0 and 5 index

In [38]:
COVID19data_df.iloc[0:3, [0, 5]]

    Country  Population
0   Burundi    12029114
1  Ethiopia   116082175
2     Kenya    54237961

In example 2, we selected the first three observations and variables Country and Population. 

**Important note**

Please note that `.iloc[]` index position is exclusive i.e. $0 : 3$ means $0, 1, 2$. This is like Numpy array.

## Example 2

Select all the observations and columns Gender and Age in the students registration list using 

1. `.iloc[]` attribute

2. `.loc[]` attribute

In [39]:
registrations_df

    Country  Gender  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

With **.iloc[]** attribute

In [40]:
registrations_df.iloc[:, [1, 2]] # .iloc[] selection is by the position.

   Gender  Age
0    Male   11
1  Female   17
2  Female   15
3  Female   17
4    Male   13
5  Female   11
6    Male    9
7  Female   18
8    Male   13
9  Female   16

With **loc[]** attribute

In [41]:
registrations_df.loc[:, ["Gender", "Age"]] # .loc[] selection is by the label.

   Gender  Age
0    Male   11
1  Female   17
2  Female   15
3  Female   17
4    Male   13
5  Female   11
6    Male    9
7  Female   18
8    Male   13
9  Female   16

# How to rename column names in a DataFrame

We can use the `.rename()` method to rename certain or all columns in a DataFrame via a `dict` (dictionary). Let's rename `Total Cases` to `COVID-19 cases`, and `Total Deaths` to `COVID-19 Death cases` in our `COVID19data_df` that is shown below:

In [42]:
COVID19data_df

,Country,Total Cases,Total Deaths,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

In [43]:
COVID19data_df.rename(columns= {
    "Total Cases": "COVID-19 Cases", 
    "Total Deaths": "COVID-19 Death Cases"
})

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

As you can see, the `.rename()` attribute takes the `columns` as the input in which we pass the dictionary containing the the old and new column names that we want to rename in the DataFrame. The result is not save to any variable until we save it. This happens because Pandas wants to show us whether our output or result is correct and we can amend or save automatically with the `inplace` argument as shown below:

In [44]:
COVID19data_df.rename(columns= {
    "Total Cases": "COVID-19 Cases", 
    "Total Deaths": "COVID-19 Death Cases"
}, inplace= True)

We can see the result by calling out `COVID19data_df`

In [45]:
COVID19data_df

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789
5,Tanzania,509,21,183,305,60399786
6,Uganda,18406,186,8764,9456,46304101
7,Sudan,16431,1202,9854,5375,44252054

## Example 2

Using students registration dataframe, rename `Gender` to `Sex`

In [46]:
registrations_df

    Country  Gender  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

In [47]:
registrations_df.rename(columns={
    "Gender": "Sex"
}, inplace=True)

In [48]:
registrations_df

    Country     Sex  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

# Adding a Column to Your DataFrame

We can create a new column called `Fatality rate` from our COVID-19 data. $\text{Fatality rate} = \frac{\text{COVID-19 Death Cases}}{\text{COVID-19 Cases}}$

Fatatlity rate is the proportion of deaths from a certain disease compared to the total number of people diagnosed with the disease for a particular period.

Let's see the quick overview of `COVID19data_df` DataFrame

In [49]:
COVID19data_df.head()

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population
0,Burundi,673,1,575,97,12029114
1,Ethiopia,107109,1664,66574,38871,116082175
2,Kenya,79322,1417,52974,24931,54237961
3,Rwanda,5750,47,5241,462,13078334
4,Somalia,4445,113,3412,920,16066789

In [50]:
COVID19data_df["COVID-19 Cases"]

0       673
1    107109
2     79322
3      5750
4      4445
5       509
6     18406
7     16431
Name: COVID-19 Cases, dtype: int64

We want to calculate the fatality rate of COVID-19 for each of the countries. Do you remember how to get or extract a series from a DataFrame? 

**Hint**: `df.column_name` or `df["column_name]`.

In [51]:
COVID19data_df["Fatality rate"] = COVID19data_df["COVID-19 Death Cases"]/COVID19data_df["COVID-19 Cases"]

`COVID19data_df["Fatality rate"]` is our new series or column while `COVID19data_df["COVID-19 Death Cases"]` and `COVID19data_df["COVID-19 Cases"]` are the existing series that we want to use to get the new column. The resulting Dataframe is shown below:

In [52]:
COVID19data_df

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population,Fatality rate
0,Burundi,673,1,575,97,12029114,0.001486
1,Ethiopia,107109,1664,66574,38871,116082175,0.015536
2,Kenya,79322,1417,52974,24931,54237961,0.017864
3,Rwanda,5750,47,5241,462,13078334,0.008174
4,Somalia,4445,113,3412,920,16066789,0.025422
5,Tanzania,509,21,183,305,60399786,0.041257
6,Uganda,18406,186,8764,9456,46304101,0.010105
7,Sudan,16431,1202,9854,5375,44252054,0.073154

# Example 2

Create a new column called `Discharge rate` from the COVID-19 DataFrame. $\text{Discharge rate} = \frac{\text{Total Recovered}}{\text{COVID-19 Cases}}$.

Discharge rate is the proportion of people that recovered from a certain disease compared to the total number of people diagnosed with the disease for a particular period.

In [53]:
COVID19data_df["Discharge rate"] = COVID19data_df["Total Recovered"]/COVID19data_df["COVID-19 Cases"]

and the resulting DataFrame is:

In [54]:
COVID19data_df

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population,Fatality rate,Discharge rate
0,Burundi,673,1,575,97,12029114,0.001486,0.854383
1,Ethiopia,107109,1664,66574,38871,116082175,0.015536,0.621554
2,Kenya,79322,1417,52974,24931,54237961,0.017864,0.667835
3,Rwanda,5750,47,5241,462,13078334,0.008174,0.911478
4,Somalia,4445,113,3412,920,16066789,0.025422,0.767604
5,Tanzania,509,21,183,305,60399786,0.041257,0.359528
6,Uganda,18406,186,8764,9456,46304101,0.010105,0.476149
7,Sudan,16431,1202,9854,5375,44252054,0.073154,0.599720

# Dropping/Removing Columns from a DataFrame

You can drop or remove a column from an existing DataFrame by using `.drop()` attribute. In this section, we use DataFrames namely `registrations_df` and `COVID19data_df`

In [55]:
registrations_df.head()

    Country     Sex  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13

## Example 1

Let's drop the `Country` column from the `registrations_df`

In [56]:
registrations_df.drop("Country", axis = "columns")

      Sex  Age
0    Male   11
1  Female   17
2  Female   15
3  Female   17
4    Male   13
5  Female   11
6    Male    9
7  Female   18
8    Male   13
9  Female   16

As we can see from the resulting DataFrame that the column `Country` has been dropped. We specified axis to be "columns" to show that what we want to drop is from the columns. The `axis` arguement takes two values; 1 (or "columns") to drop columns and 0 (or "rows") to drop index.

We can save the resulting DataFrame as a new DataFrame `registrations_df_drop` or use `inplace = True` to replace the original DataFrame

In [57]:
registrations_df_drop = registrations_df.drop("Age", axis = "columns")

In [58]:
registrations_df_drop

    Country     Sex
0    Uganda    Male
1  Ethiopia  Female
2    Rwanda  Female
3   Somalia  Female
4     Sudan    Male
5     Kenya  Female
6    Uganda    Male
7     Kenya  Female
8   Somalia    Male
9    Rwanda  Female

## Example 2
Let's drop the `Active Cases` and `Population`columns from the `COVID19data_df` DataFrame

In [59]:
COVID19data_df

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population,Fatality rate,Discharge rate
0,Burundi,673,1,575,97,12029114,0.001486,0.854383
1,Ethiopia,107109,1664,66574,38871,116082175,0.015536,0.621554
2,Kenya,79322,1417,52974,24931,54237961,0.017864,0.667835
3,Rwanda,5750,47,5241,462,13078334,0.008174,0.911478
4,Somalia,4445,113,3412,920,16066789,0.025422,0.767604
5,Tanzania,509,21,183,305,60399786,0.041257,0.359528
6,Uganda,18406,186,8764,9456,46304101,0.010105,0.476149
7,Sudan,16431,1202,9854,5375,44252054,0.073154,0.599720

We can pass the list containing the names of the columns to drop in the `.drop()` attribute. For example:

In [62]:
COVID19data_df.drop(["Active Cases", "Population"], axis = "columns") 
# remember to remove column(s) we can specify axis = 1 or "columns"

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Fatality rate,Discharge rate
0,Burundi,673,1,575,0.001486,0.854383
1,Ethiopia,107109,1664,66574,0.015536,0.621554
2,Kenya,79322,1417,52974,0.017864,0.667835
3,Rwanda,5750,47,5241,0.008174,0.911478
4,Somalia,4445,113,3412,0.025422,0.767604
5,Tanzania,509,21,183,0.041257,0.359528
6,Uganda,18406,186,8764,0.010105,0.476149
7,Sudan,16431,1202,9854,0.073154,0.599720

**Note**: It is important to save the resulting DataFrame.

In [63]:
COVID19data_df_drop = COVID19data_df.drop(["Active Cases", "Population"], axis = 1)

and if we use `COVID19data_df.drop(["Active Cases", "Population"], axis = 1, implace = True)`, that will replace the full DataFrame to a DataFrame where columns "Active Cases" and "Population" has been removed or droped. That may be dangerous because you have destroyed the original DataFrame with the `inplace = True`.

In [65]:
new_covid19 = COVID19data_df.drop(["Active Cases", "Population"], axis = "columns")

In [66]:
new_covid19

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Fatality rate,Discharge rate
0,Burundi,673,1,575,0.001486,0.854383
1,Ethiopia,107109,1664,66574,0.015536,0.621554
2,Kenya,79322,1417,52974,0.017864,0.667835
3,Rwanda,5750,47,5241,0.008174,0.911478
4,Somalia,4445,113,3412,0.025422,0.767604
5,Tanzania,509,21,183,0.041257,0.359528
6,Uganda,18406,186,8764,0.010105,0.476149
7,Sudan,16431,1202,9854,0.073154,0.599720

In [70]:
new_covid19.drop(["COVID-19 Death Cases", "Discharge rate"], axis = "columns", inplace = True)

In [71]:
new_covid19

    Country  COVID-19 Cases  Total Recovered  Fatality rate
0   Burundi             673              575       0.001486
1  Ethiopia          107109            66574       0.015536
2     Kenya           79322            52974       0.017864
3    Rwanda            5750             5241       0.008174
4   Somalia            4445             3412       0.025422
5  Tanzania             509              183       0.041257
6    Uganda           18406             8764       0.010105
7     Sudan           16431             9854       0.073154

## Conditional filtering of a DataFrame

You can filter a DataFrame based on a condition of one or more Series in the DataFrame.

## Example 1

In our `registrations_df` DataFrame, we can show a DataFrame where only `Female` are available:

In [72]:
registrations_df

    Country     Sex  Age
0    Uganda    Male   11
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
4     Sudan    Male   13
5     Kenya  Female   11
6    Uganda    Male    9
7     Kenya  Female   18
8   Somalia    Male   13
9    Rwanda  Female   16

**Step 1:**
    
Select `Gender` Series from the DataFrame

In [74]:
step1 = registrations_df["Sex"]

step1

0      Male
1    Female
2    Female
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: Sex, dtype: object

**Step 2:**
    
Use comparison `==` operator to distinguish whether they are "Female" or not.

In [75]:
step2 = registrations_df["Sex"] == "Female"

step2

0    False
1     True
2     True
3     True
4    False
5     True
6    False
7     True
8    False
9     True
Name: Sex, dtype: bool

**Step 3:**
    
Use the result of step 2 to select/filter the `registrations_df` DataFrame

In [76]:
registrations_df[step2]

    Country     Sex  Age
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
5     Kenya  Female   11
7     Kenya  Female   18
9    Rwanda  Female   16

We do step 1 to 3 in one line of code as shown below:

In [78]:
registrations_df[registrations_df["Sex"] == "Female"]

    Country     Sex  Age
1  Ethiopia  Female   17
2    Rwanda  Female   15
3   Somalia  Female   17
5     Kenya  Female   11
7     Kenya  Female   18
9    Rwanda  Female   16

In [79]:
registrations_df[registrations_df["Sex"] == "Male"]

   Country   Sex  Age
0   Uganda  Male   11
4    Sudan  Male   13
6   Uganda  Male    9
8  Somalia  Male   13

## Example 2

In the `COVID19data_df` DataFrame, show a DataFrame where:
    
1. COVID-19 Cases is less than 3000
  - The resulting DataFrame has how many rows?
2. COVID-19 Death Cases is less than 50 and and Total Recovered is 200
    - The resulting DataFrame has how many rows?

In [80]:
COVID19data_df

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population,Fatality rate,Discharge rate
0,Burundi,673,1,575,97,12029114,0.001486,0.854383
1,Ethiopia,107109,1664,66574,38871,116082175,0.015536,0.621554
2,Kenya,79322,1417,52974,24931,54237961,0.017864,0.667835
3,Rwanda,5750,47,5241,462,13078334,0.008174,0.911478
4,Somalia,4445,113,3412,920,16066789,0.025422,0.767604
5,Tanzania,509,21,183,305,60399786,0.041257,0.359528
6,Uganda,18406,186,8764,9456,46304101,0.010105,0.476149
7,Sudan,16431,1202,9854,5375,44252054,0.073154,0.599720

## Solution 1

- COVID-19 Cases is less than 3000
  - The resulting DataFrame has how many rows?

In [81]:
COVID19data_df_sol1 = COVID19data_df[COVID19data_df["COVID-19 Cases"] <3000]

COVID19data_df_sol1

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population,Fatality rate,Discharge rate
0,Burundi,673,1,575,97,12029114,0.001486,0.854383
5,Tanzania,509,21,183,305,60399786,0.041257,0.359528

In [82]:
COVID19data_df_sol1.shape

(2, 8)

There are two rows in this DataFrame

## Solution 2

- COVID-19 Death Cases is less than $50$ and and Total Recovered is less than $200$
    - The resulting DataFrame has how many rows?
    
As we can see from the question that the condition is based on two Series/columns 

1. COVID-19 Death Cases is less than $50$ 

2. Total Recovered is less than $200$

In [83]:
COVID19data_df_sol2 = COVID19data_df[(COVID19data_df["COVID-19 Death Cases"] < 50) & (COVID19data_df["Total Recovered"] < 200)]

COVID19data_df_sol2

,Country,COVID-19 Cases,COVID-19 Death Cases,Total Recovered,Active Cases,Population,Fatality rate,Discharge rate
5,Tanzania,509,21,183,305,60399786,0.041257,0.359528

In [84]:
COVID19data_df_sol2.shape

(1, 8)

The resulting DataFrame has just one row.

## Review of DataFrame

We have learnt Pandas Series and DataFrame so far and based on what you have seen and understand about Series, DataFrame, and their various attribute or methods

1. Create a DataFrame using the sample of dataset from the National Flower of Ethiopia (This was adapted from Iris data)

<img src='images/flower.jpg' alt = "Source: International Trade Center (ITR)" style="width:500; height:300"/>    


The data is shown below:

<img src='images/flower1.jpg' alt = "Source: International Trade Center (ITR)" style="width:700; height:400"/>

2. How many rows and columns are in the dataset?

3. How many series are in the DataFrame?

4. Rename `species` variable to `flower_categories`

5. Add `sepal_length` and `sepal_width` together and call the resulting series `sepal_length_width`

6. Drop the column `petal_width` from the DataFrame

7. From 6, select a DataFrame where `sepal_length` is greater than $5.5$ and name it `perfect_data`

## Solution 1

Create a DataFrame using the sample of dataset from the National Flower of Ethiopia

First, we need to import necessary libraries such as numpy, pandas, etc.

In [85]:
import numpy as np
import pandas as pd

To create a DataFrame, we need to first create a dict (dictionary) and then pass the result to DataFrame constructor

In [86]:
flower_data_dict = {"sepal_length": [5.1, 5, 5.4, 5.5, 6.5, 6.7, 7.2, 6.2], 
                    "sepal_width": [3.5, 3.6, 3.9, 2.3, 2.8, 3.3, 3.2, 2.8], 
                    "petal_length": [1.4, 1.4, 1.7, 4, 4.6, 5.7, 6, 4.8], 
                    "petal_width": [0.2, 0.2, 0.4, 1.3, 1.5, 2.1, 1.8, 1.8], 
                    "species": ["Rose", "Rose", "Rose", "Lily", "Lily", "Carnation", "Carnation", "Carnation"]
}

flower_data_dict

{'sepal_length': [5.1, 5, 5.4, 5.5, 6.5, 6.7, 7.2, 6.2],
 'sepal_width': [3.5, 3.6, 3.9, 2.3, 2.8, 3.3, 3.2, 2.8],
 'petal_length': [1.4, 1.4, 1.7, 4, 4.6, 5.7, 6, 4.8],
 'petal_width': [0.2, 0.2, 0.4, 1.3, 1.5, 2.1, 1.8, 1.8],
 'species': ['Rose',
  'Rose',
  'Rose',
  'Lily',
  'Lily',
  'Carnation',
  'Carnation',
  'Carnation']}

As you know, this is a type `dict`

In [87]:
type(flower_data_dict)

dict

We now pass the result to `pd.DataFrame()`

In [90]:
flower_data_df = pd.DataFrame(flower_data_dict)

In [91]:
flower_data_df

   sepal_length  sepal_width  petal_length  petal_width    species
0           5.1          3.5           1.4          0.2       Rose
1           5.0          3.6           1.4          0.2       Rose
2           5.4          3.9           1.7          0.4       Rose
3           5.5          2.3           4.0          1.3       Lily
4           6.5          2.8           4.6          1.5       Lily
5           6.7          3.3           5.7          2.1  Carnation
6           7.2          3.2           6.0          1.8  Carnation
7           6.2          2.8           4.8          1.8  Carnation

As you can see, the steps to creating a DataFrame are just two:
    
1. Create a dictionary for the data
2. Pass the result to pd.DataFrame() function

## Solution 2
How many rows and columns are in the dataset?

You can get the number of rows and columns in your DataFrame by using `.shape` attribute

In [93]:
flower_data_df.shape

(8, 5)

This throws an error **TypeError: 'tuple' object is not callable** because `.shape` attribute does not have a parenthesis. Please note that!

In [77]:
flower_data_df.shape

(8, 5)

The DataFrame/dataset has $8$ rows and $5$ columns

## Solution 3
How many series are in the DataFrame?

In [94]:
flower_data_df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

Series of a DataFrame is the same thing as columns or variable in that DataFrame. So therefore, we have 5 series in this dataframe

## Solution 4
rename `species` variable to `flower_categories`

To rename `species` variable to `flower_categories` we shall use `.rename()` attribute and then pass `dict` (dictionary) to it.

In [96]:
 flower_data_df.rename(columns= {
     "species": "flower_categories"
 }, inplace = True)

In [97]:
flower_data_df

   sepal_length  sepal_width  petal_length  petal_width flower_categories
0           5.1          3.5           1.4          0.2              Rose
1           5.0          3.6           1.4          0.2              Rose
2           5.4          3.9           1.7          0.4              Rose
3           5.5          2.3           4.0          1.3              Lily
4           6.5          2.8           4.6          1.5              Lily
5           6.7          3.3           5.7          2.1         Carnation
6           7.2          3.2           6.0          1.8         Carnation
7           6.2          2.8           4.8          1.8         Carnation

## Solution 5

Add `sepal_length` and `sepal_width` together and call the resulting series `sepal_length_width`

To create `sepal_length_width` series, add the series of `sepal_length` and `sepal_width` togther.

In [98]:
flower_data_df["sepal_length_width"] = flower_data_df["sepal_length"] + flower_data_df["sepal_width"]
flower_data_df

,sepal_length,sepal_width,petal_length,petal_width,flower_categories,sepal_length_width
0,5.1,3.5,1.4,0.2,Rose,8.6
1,5.0,3.6,1.4,0.2,Rose,8.6
2,5.4,3.9,1.7,0.4,Rose,9.3
3,5.5,2.3,4.0,1.3,Lily,7.8
4,6.5,2.8,4.6,1.5,Lily,9.3
5,6.7,3.3,5.7,2.1,Carnation,10.0
6,7.2,3.2,6.0,1.8,Carnation,10.4
7,6.2,2.8,4.8,1.8,Carnation,9.0

## Solution 6

Drop the column `petal_width` from the DataFrame

In [99]:
flower_data_df.drop(["petal_width"])

KeyError: "['petal_width'] not found in axis"

This threw an error because axis argument has not been specified.

In [100]:
flower_data_df.drop(["petal_width"], axis = "columns")

,sepal_length,sepal_width,petal_length,flower_categories,sepal_length_width
0,5.1,3.5,1.4,Rose,8.6
1,5.0,3.6,1.4,Rose,8.6
2,5.4,3.9,1.7,Rose,9.3
3,5.5,2.3,4.0,Lily,7.8
4,6.5,2.8,4.6,Lily,9.3
5,6.7,3.3,5.7,Carnation,10.0
6,7.2,3.2,6.0,Carnation,10.4
7,6.2,2.8,4.8,Carnation,9.0

petal_width has been removed from the columns. Let's save the result as `flower_data_df_drop`

In [102]:
flower_data_df_drop = flower_data_df.drop(["petal_width"], axis = "columns")

flower_data_df_drop

,sepal_length,sepal_width,petal_length,flower_categories,sepal_length_width
0,5.1,3.5,1.4,Rose,8.6
1,5.0,3.6,1.4,Rose,8.6
2,5.4,3.9,1.7,Rose,9.3
3,5.5,2.3,4.0,Lily,7.8
4,6.5,2.8,4.6,Lily,9.3
5,6.7,3.3,5.7,Carnation,10.0
6,7.2,3.2,6.0,Carnation,10.4
7,6.2,2.8,4.8,Carnation,9.0

## Solution 7
From solution $6$, select a DataFrame where `sepal_length` is greater than  5.5  and name it `perfect_data`

We shall use our new DataFrame `flower_data_df_drop` to filter where sepal_length is greater than 5.5

In [103]:
perfect_data = flower_data_df_drop[flower_data_df_drop["sepal_length"]> 5.5]

perfect_data

,sepal_length,sepal_width,petal_length,flower_categories,sepal_length_width
4,6.5,2.8,4.6,Lily,9.3
5,6.7,3.3,5.7,Carnation,10.0
6,7.2,3.2,6.0,Carnation,10.4
7,6.2,2.8,4.8,Carnation,9.0