# Combining and Merging Datasets

It’s rare that a data analysis involves only a single table of data. Typically you have many tables of data, and you must combine them to answer the questions that you’re interested in. Collectively, multiple tables of data are called relational data because it is the relations, not just the individual datasets, that are important.

Relations are always defined between a pair of tables. All other relations are built up from this simple idea: the relations of three or more tables are always a property of the relations between each pair. Sometimes both elements of a pair can be the same table! This is needed if, for example, you have a table of people, and each person has a reference to their parents.

For example consider the two DataFrames below:

In [187]:
COVID19_info_dic = {"Country": ["Burundi", "Ethiopia", "Kenya", "Rwanda", "Somalia", "Tanzania", "Uganda", "Sudan"],
               "Confirmed cases": [673, 107109, 79322, 5750, 4445, 509, 18406, 16431],
               "Death cases": [1, 1664, 1417, 47, 113, 21, 186, 1202],
               "Recovered cases": [575, 66574, 52974, 5241, 3412, 183, 8764, 9854],
               "Population" : [12029114, 116082175, 54237961, 13078334, 16066789, 60399786, 46304101, 44252054]
}

COVID19_info_df = pd.DataFrame(COVID19data, columns= ["Country", "Total Cases", "Total Deaths", "Total Recovered", "Population"])

COVID19_info_df

    Country  Total Cases  Total Deaths  Total Recovered  Population
0   Burundi          673             1              575    12029114
1  Ethiopia       107109          1664            66574   116082175
2     Kenya        79322          1417            52974    54237961
3    Rwanda         5750            47             5241    13078334
4   Somalia         4445           113             3412    16066789
5  Tanzania          509            21              183    60399786
6    Uganda        18406           186             8764    46304101
7     Sudan        16431          1202             9854    44252054

In [188]:
epidemiology_info_dic = {"Country": ["Burundi", "Ethiopia", "Kenya", "Rwanda", "Somalia", "Tanzania", "Uganda", "Sudan"],

"Fatality rate" : [0.001, 0.016, 0.018, 0.008, 0.025, 0.041, 0.010,  0.073],

"Discharge rate" : [0.854, 0.622, 0.668, 0.911, 0.768, 0.360, 0.476, 0.600]
}

epidemiology_info_df = pd.DataFrame(epidemiology_info_dic, columns= ["Country", "Fatality rate", "Discharge rate"])

epidemiology_info_df

    Country  Fatality rate  Discharge rate
0   Burundi          0.001           0.854
1  Ethiopia          0.016           0.622
2     Kenya          0.018           0.668
3    Rwanda          0.008           0.911
4   Somalia          0.025           0.768
5  Tanzania          0.041           0.360
6    Uganda          0.010           0.476
7     Sudan          0.073           0.600

#  Keys
The variables used to connect each pair of tables are called keys. A key is a variable (or set of variables) that uniquely identifies an observation. In simple cases, a single variable is sufficient to identify an observation. For example, each COVID-19 data  is uniquely identified by their country name. In other cases, multiple variables may be needed. 

There are two types of keys:

A **primary key** uniquely identifies an observation in its own table. For example, `COVID19_info_df["Country"]` is a primary key because it uniquely identifies each COVID-19 cases in the COVID-19 DataFame.

A **foreign key** uniquely identifies an observation in another table. For example, `epidemiology_info_df["Country]` is a foreign key because it appears in the COVID-19 DataFame where it matches each country to a unique COVID-19 cases.

---
Data contained in pandas objects can be combined together in a number of ways:

* `pd.merge` connects rows in DataFrames based on one or more keys. 

* `pd.concat` concatenates or “stacks” together objects along an axis.

## Joining/merging DataFrames with `pd.merge()` function

`pd.merge()` combine datasets by linking rows using one or more keys. There are 4 types of joining.

**Type of merge to be performed includes**: 

- left: use only keys from the left DataFrame

- right: use only keys from the right DataFrame

- outer: use union of keys from both DataFrames

- inner: use intersection of keys from both DataFrames


`pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)

Some of the key parameters are:

`left`: The first DataFrame

`right`: The second DataFrame

`on`: Column to join on. 

`how`: One of 'left', 'right', 'outer', 'inner'. Defaults to inner. 

The left `left_on` and `right_on` are useful when primary and foreign keys have different names (column names)

`left_on`: Columns from the left DataFrame to use as keys. Can either be column names, index level names, or arrays with length equal to the length of the DataFrame or Series.

`right_on`: Columns or index levels from the right DataFrame or Series to use as keys. Can either be column names, index level names, or arrays with length equal to the length of the DataFrame or Series.

## Example 1

Consider `COVID19_info_df` and `epidemiology_info_df` DataFrames.

In [189]:
COVID19_info_df.head()

    Country  Total Cases  Total Deaths  Total Recovered  Population
0   Burundi          673             1              575    12029114
1  Ethiopia       107109          1664            66574   116082175
2     Kenya        79322          1417            52974    54237961
3    Rwanda         5750            47             5241    13078334
4   Somalia         4445           113             3412    16066789

In [190]:
epidemiology_info_df.head()

    Country  Fatality rate  Discharge rate
0   Burundi          0.001           0.854
1  Ethiopia          0.016           0.622
2     Kenya          0.018           0.668
3    Rwanda          0.008           0.911
4   Somalia          0.025           0.768

We can perform left merging or joining by using:

In [191]:
country_info = pd.merge(COVID19_info_df, epidemiology_info_df, on = "Country", how = "left")

country_info

,Country,Total Cases,Total Deaths,Total Recovered,Population,Fatality rate,Discharge rate
0,Burundi,673,1,575,12029114,0.001,0.854
1,Ethiopia,107109,1664,66574,116082175,0.016,0.622
2,Kenya,79322,1417,52974,54237961,0.018,0.668
3,Rwanda,5750,47,5241,13078334,0.008,0.911
4,Somalia,4445,113,3412,16066789,0.025,0.768
5,Tanzania,509,21,183,60399786,0.041,0.360
6,Uganda,18406,186,8764,46304101,0.010,0.476
7,Sudan,16431,1202,9854,44252054,0.073,0.600

As you can see, the two datasets have been merge together.

## Example 2

Consider `band_members` and `band_instruments` DataFrames below:

In [192]:
band_members = pd.DataFrame({"name" : ["Mick", "John", "Paul"], "band": ["Stones", "Beatles", "Beatles"]})

band_members

   name     band
0  Mick   Stones
1  John  Beatles
2  Paul  Beatles

In [193]:
band_instruments = pd.DataFrame({"name" :["John", "Paul", "Keith"], "plays": ["guitar", "bass", "guitar"]})
band_instruments

    name   plays
0   John  guitar
1   Paul    bass
2  Keith  guitar

## Use inner join to combine `band_members` and `band_instruments` DataFrames

In [194]:
inner_join = pd.merge(band_members, band_instruments, on = "name", how = "inner")

inner_join

   name     band   plays
0  John  Beatles  guitar
1  Paul  Beatles    bass

inner join uses intersection of keys from both DataFrames and includes all rows where there is an intersection

## Use  left join to combine `band_members` and `band_instruments` DataFrames

In [195]:
left_join = pd.merge(band_members, band_instruments, on = "name", how = "left")

left_join

   name     band   plays
0  Mick   Stones     NaN
1  John  Beatles  guitar
2  Paul  Beatles    bass

left join uses only keys from the left DataFrame and includes all its rows in the mergin.

## Use  right join to combine `band_members` and `band_instruments` DataFrames

In [196]:
right_join = pd.merge(band_members, band_instruments, on = "name", how = "right")

right_join

    name     band   plays
0   John  Beatles  guitar
1   Paul  Beatles    bass
2  Keith      NaN  guitar

right join uses only keys from the right DataFrame and includes all its rows for the mergin.

## Use outer join to combine `band_members` and `band_instruments` DataFrames

In [197]:
outer_join = pd.merge(band_members, band_instruments, on = "name", how = "outer")

outer_join

    name     band   plays
0   Mick   Stones     NaN
1   John  Beatles  guitar
2   Paul  Beatles    bass
3  Keith      NaN  guitar

outer join also known as full join uses union of keys from both DataFrames and includes all rows in the two DataFrames for the mergin.