   
<img src='images/Pandas.png' alt = "Pandas" style="width:600; height:300"/>

# Concatenating DataFrames with `pd.concat()` function

To simply concatenate or combine the DataFrames along the row you can use the `pd.concat()` function in pandas. You will have to pass the names of the DataFrames in a list as the argument to the `pd.concat()` function.

## Note

DataFrames to be concatenated/combined must have the same columns names.

## Example 1

Let's import `east_africa.csv` and `central_africa.csv` COVID-19 datasets which can be found the `datasets` directory and combine them using `pd.concat()`.

We shall import the dataset using a relative path `datasets/...`

In [198]:
east_africa_covid = pd.read_csv("datasets/east_africa.csv")

east_africa_covid.head()

,Country,Region,Total Cases,Total Deaths,Total Recovered,Active Cases,Serious_Critical,Population,Total Tests,Tests/1M pop
0,Burundi,East Africa,694,1.0,575,118,NaN,12039804,62215.0,5167.0
1,Comoros,East Africa,616,7.0,600,9,NaN,877463,NaN,NaN
2,Djibouti,East Africa,5701,61.0,5593,47,NaN,994138,93540.0,94092.0
3,Eritrea,East Africa,632,NaN,508,124,NaN,3567406,21655.0,6070.0
4,Ethiopia,East Africa,113295,1747.0,80831,30717,317.0,116168018,1669754.0,14374.0

In [199]:
centra_africa_covid = pd.read_csv("datasets/central_africa.csv")

centra_africa_covid.head()

,Country,Region,Total Cases,Total Deaths,Total Recovered,Active Cases,Serious_Critical,Population,Total Tests,Tests/1M pop
0,Angola,Central Africa,15536,354,8335,6847,14.0,33295883,171247.0,5143.0
1,Cameroon,Central Africa,24752,443,23344,965,52.0,26825311,149000.0,5554.0
2,Central African Republic,Central Africa,4922,63,1924,2935,2.0,4865546,32711.0,6723.0
3,Chad,Central Africa,1725,102,1564,59,NaN,16624422,NaN,NaN
4,Congo,Central Africa,5774,94,4988,692,NaN,5575542,NaN,NaN

We can combine the two DataFrames by passing the names of the DataFrames in a list as the argument to the `pd.concat()` function.

In [200]:
east_and_centra_africa_covid19 =  pd.concat([east_africa_covid, centra_africa_covid])

east_and_centra_africa_covid19

,Country,Region,Total Cases,Total Deaths,Total Recovered,Active Cases,Serious_Critical,Population,Total Tests,Tests/1M pop
0,Burundi,East Africa,694,1.0,575,118,NaN,12039804,62215.0,5167.0
1,Comoros,East Africa,616,7.0,600,9,NaN,877463,NaN,NaN
2,Djibouti,East Africa,5701,61.0,5593,47,NaN,994138,93540.0,94092.0
3,Eritrea,East Africa,632,NaN,508,124,NaN,3567406,21655.0,6070.0
4,Ethiopia,East Africa,113295,1747.0,80831,30717,317.0,116168018,1669754.0,14374.0
5,Kenya,East Africa,88380,1526.0,68929,17925,76.0,54273641,927082.0,17082.0
6,Madagascar,East Africa,17513,255.0,16927,331,16.0,27991823,95472.0,3411.0
7,Malawi,East Africa,6051,185.0,5476,390,4.0,19338802,76148.0,3938.0
8,Mauritius,East Africa,508,10.0,465,33,NaN,1272680,289552.0,227514.0
9,Mayotte,East Africa,5181,49.0,2964,2168,4.0,275601,25231.0,91549.0
10,Mozambique,East Africa,16244,133.0,14416,1695,NaN,31624580,238362.0,7537.0
11,Rwanda,East Africa,6129,51.0,5696,382,NaN,13088013,644631.0,49254.0
12,Seychelles,East Africa,184,NaN,168,16,NaN,98609,5200.0,52734.0
13,Somalia,East Africa,4525,121.0,3480,924,NaN,16080166,NaN,NaN
14,South Sudan,East Africa,3166,62.0,2977,127,1.0,11249945,61964.0,5508.0
15,Tanzania,East Africa,509,21.0,183,305,7.0,60451126,NaN,NaN
16,Uganda,East Africa,22499,206.0,9175,13118,NaN,46347726,641893.0,13850.0
17,Zambia,East Africa,17916,364.0,17173,379,NaN,18600999,440644.0,23689.0
18,Zimbabwe,East Africa,10718,291.0,8880,1547,NaN,14955363,186397.0,12464.0
0,Angola,Central Africa,15536,354.0,8335,6847,14.0,33295883,171247.0,5143.0
1,Cameroon,Central Africa,24752,443.0,23344,965,52.0,26825311,149000.0,5554.0
2,Central African Republic,Central Africa,4922,63.0,1924,2935,2.0,4865546,32711.0,6723.0
3,Chad,Central Africa,1725,102.0,1564,59,NaN,16624422,NaN,NaN
4,Congo,Central Africa,5774,94.0,4988,692,NaN,5575542,NaN,NaN
5,DRC,Central Africa,13413,342.0,11857,1214,NaN,90706416,NaN,NaN
6,Equatorial Guinea,Central Africa,5159,85.0,5023,51,NaN,1422319,70998.0,49917.0
7,Gabon,Central Africa,9254,60.0,9106,88,6.0,2247973,311091.0,138387.0
8,Sao Tome and Principe,Central Africa,999,17.0,937,45,NaN,220891,7498.0,33944.0

You will notice that the two DataFrames `east_africa_covid` and `centra_africa_covid` are now concatenated or combined into a single DataFrame called `east_and_centra_africa_covid19` along the row. However, the row labels seem to be wrong! If you want the row labels to adjust automatically according to the join, you will have to set the argument `ignore_index` as True while calling the `pd.concat()` function:

In [201]:
east_and_centra_africa_covid19 =  pd.concat([east_africa_covid, centra_africa_covid], ignore_index = True)

east_and_centra_africa_covid19

,Country,Region,Total Cases,Total Deaths,Total Recovered,Active Cases,Serious_Critical,Population,Total Tests,Tests/1M pop
0,Burundi,East Africa,694,1.0,575,118,NaN,12039804,62215.0,5167.0
1,Comoros,East Africa,616,7.0,600,9,NaN,877463,NaN,NaN
2,Djibouti,East Africa,5701,61.0,5593,47,NaN,994138,93540.0,94092.0
3,Eritrea,East Africa,632,NaN,508,124,NaN,3567406,21655.0,6070.0
4,Ethiopia,East Africa,113295,1747.0,80831,30717,317.0,116168018,1669754.0,14374.0
5,Kenya,East Africa,88380,1526.0,68929,17925,76.0,54273641,927082.0,17082.0
6,Madagascar,East Africa,17513,255.0,16927,331,16.0,27991823,95472.0,3411.0
7,Malawi,East Africa,6051,185.0,5476,390,4.0,19338802,76148.0,3938.0
8,Mauritius,East Africa,508,10.0,465,33,NaN,1272680,289552.0,227514.0
9,Mayotte,East Africa,5181,49.0,2964,2168,4.0,275601,25231.0,91549.0
10,Mozambique,East Africa,16244,133.0,14416,1695,NaN,31624580,238362.0,7537.0
11,Rwanda,East Africa,6129,51.0,5696,382,NaN,13088013,644631.0,49254.0
12,Seychelles,East Africa,184,NaN,168,16,NaN,98609,5200.0,52734.0
13,Somalia,East Africa,4525,121.0,3480,924,NaN,16080166,NaN,NaN
14,South Sudan,East Africa,3166,62.0,2977,127,1.0,11249945,61964.0,5508.0
15,Tanzania,East Africa,509,21.0,183,305,7.0,60451126,NaN,NaN
16,Uganda,East Africa,22499,206.0,9175,13118,NaN,46347726,641893.0,13850.0
17,Zambia,East Africa,17916,364.0,17173,379,NaN,18600999,440644.0,23689.0
18,Zimbabwe,East Africa,10718,291.0,8880,1547,NaN,14955363,186397.0,12464.0
19,Angola,Central Africa,15536,354.0,8335,6847,14.0,33295883,171247.0,5143.0
20,Cameroon,Central Africa,24752,443.0,23344,965,52.0,26825311,149000.0,5554.0
21,Central African Republic,Central Africa,4922,63.0,1924,2935,2.0,4865546,32711.0,6723.0
22,Chad,Central Africa,1725,102.0,1564,59,NaN,16624422,NaN,NaN
23,Congo,Central Africa,5774,94.0,4988,692,NaN,5575542,NaN,NaN
24,DRC,Central Africa,13413,342.0,11857,1214,NaN,90706416,NaN,NaN
25,Equatorial Guinea,Central Africa,5159,85.0,5023,51,NaN,1422319,70998.0,49917.0
26,Gabon,Central Africa,9254,60.0,9106,88,6.0,2247973,311091.0,138387.0
27,Sao Tome and Principe,Central Africa,999,17.0,937,45,NaN,220891,7498.0,33944.0

## Example 2
Let's import `north_africa.csv` and combine them to `east_and_centra_africa_covid19` DataFrame using `pd.concat()`.

In [202]:
north_africa_covid = pd.read_csv("datasets/north_africa.csv")

north_africa_covid.head()

,Country,Region,Total Cases,Total Deaths,Total Recovered,Active Cases,Serious_Critical,Population,Total Tests,Tests/1M pop
0,Algeria,North Africa,88252,2516,57146,88252,46.0,44188203,NaN,NaN
1,Egypt,North Africa,118014,6750,103324,7940,46.0,103155589,1000000.0,9694.0
2,Libya,North Africa,86580,1231,56702,28647,NaN,6911249,458079.0,66280.0
3,Morocco,North Africa,379657,6245,331301,42111,940.0,37097956,4074451.0,109830.0
4,Sudan,North Africa,19196,1290,10942,6964,NaN,44282906,NaN,NaN

In [203]:
north_east_centra = pd.concat([north_africa_covid, east_and_centra_africa_covid19], ignore_index=True)

north_east_centra.head()

,Country,Region,Total Cases,Total Deaths,Total Recovered,Active Cases,Serious_Critical,Population,Total Tests,Tests/1M pop
0,Algeria,North Africa,88252,2516.0,57146,88252,46.0,44188203,NaN,NaN
1,Egypt,North Africa,118014,6750.0,103324,7940,46.0,103155589,1000000.0,9694.0
2,Libya,North Africa,86580,1231.0,56702,28647,NaN,6911249,458079.0,66280.0
3,Morocco,North Africa,379657,6245.0,331301,42111,940.0,37097956,4074451.0,109830.0
4,Sudan,North Africa,19196,1290.0,10942,6964,NaN,44282906,NaN,NaN